apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-conjur-oss
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
---
apiVersion: {{ include "conjur-oss.rbac-api" . }}
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-conjur-authenticator
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
---
kind: ClusterRoleBinding
apiVersion: {{ include "conjur-oss.rbac-api" . }}
metadata:
  name: {{ .Release.Name }}-conjur-authenticator
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-conjur-oss
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-conjur-authenticator
  apiGroup: rbac.authorization.k8s.io