{{- if .Values.ingress.enabled -}}
{{- $fullName := include "conjur-oss.fullname" . -}}
{{- $altNames := .Values.ssl.altNames -}}
{{- $letsencrypt := .Values.ingress.tls.letsencrypt -}}
{{- if $letsencrypt.enabled -}}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}-certificate
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: service
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  secretName: {{ $fullName }}-certificate-secret
  issuerRef:
    name: {{ $letsencrypt.issuerRef.name | quote }}
    kind: {{ $letsencrypt.issuerRef.kind | quote }}
  commonName: {{ .Values.ssl.hostname | quote }}
  dnsNames:
    - {{ .Values.ssl.hostname }}
  {{- range $altNames }}
    - {{ . }}
  {{- end }}
  acme:
    config:
    - dns01:
        provider: {{ $letsencrypt.dns01.provider | quote }}
      domains:
        - {{ .Values.ssl.hostname }}
      {{- range $altNames }}
        - {{ . }}
      {{- end }}
{{- end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: service
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ printf "%s." .Values.ssl.hostname }}
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{ end -}}
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: https
{{- if $letsencrypt.enabled }}
  tls:
    - secretName: {{ $fullName }}-certificate-secret
      hosts:
        - {{ .Values.ssl.hostname }}
      {{- range $altNames }}
        - {{ . }}
      {{- end }}
{{- end }}
{{- end }}
